Marcelo/new todo react app
dgraph-io/graphql-sample-apps pull request #250
Opened 2023-08-18 18:41 UTC by MaxxReis

* Added new todo-app using react+vite.
* New look for  todo app.
* Renamed old todo-app-react folder to todo-app-react-old

2023-08-18 19:25 UTC, MichelDiz requested changes

2023-08-18 19:25 UTC, MichelDiz commented on todo-app-react/src/components/modal.jsx
> +export default MyModal
Add new line here

2023-08-18 19:25 UTC, MichelDiz commented on todo-app-react/src/Styles/index.js
> +`;
Add new line here

2023-08-18 19:25 UTC, MichelDiz commented on todo-app-react/src/GraphQLData.js
> +`;
Add new line here

2023-08-18 19:25 UTC, MichelDiz commented on todo-app-react/public/vite.svg
Remove this or use Dgraph's one.

2023-08-18 19:25 UTC, MichelDiz commented on todo-app-react/.gitignore
> +yarn.lock
Add new line here

2023-08-18 19:40 UTC, MaxxReis commented on todo-app-react/src/components/modal.jsx
> +export default MyModal
Solved

2023-08-18 20:10 UTC, MaxxReis commented on todo-app-react/src/GraphQLData.js
> +`;
Solved

2023-08-23 20:09 UTC, MaxxReis commented on todo-app-react/public/vite.svg
Solved

2023-08-23 20:09 UTC, MaxxReis commented on todo-app-react/.gitignore
> +yarn.lock
Solved

2024-07-16 13:57 UTC, closed without merging